version: "3.9"

services:
  nextjs-app:
    image: node:20-alpine
    container_name: nxapp
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run dev -- -H 0.0.0.0"
    ports:
      - "3000:3000"
